// TermsOfService.jsx

import React from 'react';

const Privacy = () => {
  return (
    <div className="privacy-container">
      <h1>Privacy Policy</h1>
      <p>
      We are committed to maintaining the accuracy, confidentiality, and security of your personally identifiable information ("Personal Information"). As part of this commitment, our privacy policy governs our actions as they relate to the collection, use and disclosure of Personal Information. Our privacy policy is based upon the values set by the Canadian Standards Association's Model Code for the Protection of Personal Information and Canada's Personal Information Protection and Electronic Documents Act.
</p>
<p>
Definitions
For the purposes of these Terms of Service:
● “Affiliate” means an entity that controls, is controlled by or is under common control with a party,
where "control" means ownership of 50% or more of the shares, equity interest or other securities
entitled to vote for election of directors or other managing authority.</p>
<p>
● “Account” means a unique account created for You to access our Service or parts of our Service.<br></br>
● “Company” (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to
[COMPANY_INFORMATION].<br/>

● “Country” refers to [COMPANY_COUNTRY].<br/>
● “Content” refers to content such as text, images, or other information that can be posted, uploaded,
linked to or otherwise made available by You, regardless of the form of that content.<br/>
● “Device” means any device that can access the Service such as a computer, a cell phone or a
digital tablet.<br/>
● “Feedback” means feedback, innovations or suggestions sent by You regarding the attributes,
performance or features of our Service.<br/>
● “Service” refers to the Website.<br/>
● “Terms of Service” (also referred as "Terms") mean these Terms of Service that form the entire
agreement between You and the Company regarding the use of the Service. This Terms of Service
Agreement was generated by TermsFeed Terms of Service Generator.<br/>
● “Third-party Social Media Service” means any services or content (including data, information,
products or services) provided by a third-party that may be displayed, included or made available by
the Service.<br/>
● “Website” refers to [WEBSITE_NAME], accessible from [WEBSITE_URL]<br/>
● “You” means the individual accessing or using the Service, or the company, or other legal entity on
behalf of which such individual is accessing or using the Service, as applicable.</p><br/>
<h2>Acknowledgment</h2>
These are the Terms of Service governing the use of this Service and the agreement that operates between
You and the Company. These Terms of Service set out the rights and obligations of all users regarding the
use of the Service.
Your access to and use of the Service is conditioned on Your acceptance of and compliance with these
Terms of Service. These Terms of Service apply to all visitors, users and others who access or use the
Service.<br/>
By accessing or using the Service You agree to be bound by these Terms of Service. If You disagree with
any part of these Terms of Service then You may not access the Service.
You represent that you are over the age of 18. The Company does not permit those under 18 to use the
Service.<br/>
Your access to and use of the Service is also conditioned on Your acceptance of and compliance with the
Privacy Policy of the Company. Our Privacy Policy describes Our policies and procedures on the collection,
use and disclosure of Your personal information when You use the Application or the Website and tells You
about Your privacy rights and how the law protects You. Please read Our Privacy Policy carefully before
using Our Service.<br/>
<h2>User Accounts</h2>
When You create an account with Us, You must provide Us information that is accurate, complete, and
current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate
termination of Your account on Our Service.
You are responsible for safeguarding the password that You use to access the Service and for any activities
or actions under Your password, whether Your password is with Our Service or a Third-Party Social Media
Service.<br/>
You agree not to disclose Your password to any third party. You must notify Us immediately upon becoming
aware of any breach of security or unauthorized use of Your account.<br/>
You may not use as a username the name of another person or entity or that is not lawfully available for
use, a name or trademark that is subject to any rights of another person or entity other than You without
appropriate authorization, or a name that is otherwise offensive, vulgar or obscene.<br/>
<h2>Content</h2>
Your Right to Post Content<br/>
Our Service allows You to post Content. You are responsible for the Content that You post to the Service,
including its legality, reliability, and appropriateness.<br/>
By posting Content to the Service, You grant Us the right and license to use, modify, publicly perform,
publicly display, reproduce, and distribute such Content on and through the Service. You retain any and all
of Your rights to any Content You submit, post or display on or through the Service and You are responsible
for protecting those rights.<br/> You agree that this license includes the right for Us to make Your Content
available to other users of the Service, who may also use Your Content subject to these Terms.
You represent and warrant that:<br/> (i) the Content is Yours (You own it) or You have the right to use it and
grant Us the rights and license as provided in these Terms, and <br/>(ii) the posting of Your Content on or
through the Service does not violate the privacy rights, publicity rights, copyrights, contract rights or any
other rights of any person.

       
    </div>
  );
};

export default Privacy;
